enum render_command_type {
    "RENDER_COMMAND_RECTANGLE",
    "RENDER_COMMAND_HORIZONTAL_LINE"
};

interface memory_arena {
    attribute VoidPtr base;
    attribute unsigned long size;
    attribute unsigned long capacity;
};

interface render_command_header{
    attribute render_command_type type;
};

interface render_rectangle_command {
    attribute unsigned long x;
    attribute unsigned long y;
    attribute unsigned long width;
    attribute unsigned long height;
    attribute unsigned long color;
};

interface render_horizontal_line_command {
    attribute unsigned long color;
    attribute byte lineNum; // only first 256 lines
};

interface render_command_list {
    [Value] attribute memory_arena memory;
};
