enum asset_type {
    "ASSET_TYPE_IMAGE",
    "ASSET_TYPE_FONT"
};

interface image_asset {
    attribute unsigned long id;
    attribute DOMString path;
};

interface font_asset {
    attribute unsigned long id;
    attribute DOMString name;
    attribute DOMString path;
};

interface asset_to_load {
    attribute asset_type type;
    [Value] attribute image_asset image;
    [Value] attribute font_asset font;
};

interface asset_list {
    attribute asset_to_load assetsToLoad;
    attribute unsigned long numAssets;
    attribute unsigned long maxAssets;
};

interface colored_rectangle {
    attribute long x;
    attribute long y;
    attribute long width;
    attribute long height;
    attribute unsigned long color;
};

interface rectangle_list {
    attribute long numRectangles;
    attribute long maxRectangles;
    attribute colored_rectangle rectangles;
};
